# Nanobot Agent Model

## Purpose

Defines the computational agent used by the NanoSwarm simulation.

Each agent represents an autonomous simulated nanobot operating within the modeled tissue environment. The agent maintains its own state and selects movement or repair-related actions using locally available information.

The implementation is designed around decentralized decision-making rather than a centralized controller.

---

## Agent State

Each agent maintains a compact internal state containing information relevant to its current behavior.

Core state includes:

* unique agent identifier
* two-dimensional position
* velocity
* health or operational state
* current action
* local environmental observations

The position is represented in the simulation's two-dimensional coordinate system.

---

## Decision Architecture

The agent supports a hybrid movement policy combining multiple sources of information.

### Learned Policy

A Deep Q-Network can provide an action selection policy based on the agent's observed state.

The learned component is intended to capture navigation behavior that may not be represented by a simple deterministic heuristic.

### Target-Directed Heuristic

A greedy component provides a direct navigation signal toward an appropriate damaged region.

This gives the agent an explicit task-oriented behavior and provides a useful baseline for comparison.

### Pheromone Influence

The agent can also respond to the simulated pheromone field generated by the swarm.

This provides an indirect communication mechanism through the environment.

The resulting behavior can therefore combine:

**learned navigation + target-directed movement + swarm-level environmental information**

---

## Action Space

The intended movement policy uses a discrete five-action space.

The actions represent the available movement decisions defined by the simulation environment.

The action representation should remain consistent between the agent, reinforcement-learning model, and experiment runner.

---

## Velocity Smoothing

Agent movement incorporates velocity state so that changes in direction can be represented as continuous updates rather than completely independent movements at every simulation step.

Velocity smoothing is intended to reduce unrealistic instantaneous changes in direction within the computational model.

This is a modeling abstraction rather than a physical nanorobot dynamics model.

---

## Local Decision Making

The agent should make decisions using information available to it through the simulation interface.

Relevant information can include:

* nearby damage
* target direction
* distance to target
* local pheromone concentration
* local environmental state
* current velocity
* agent operational state

The architecture intentionally favors local information because decentralized coordination is a central research objective of NanoSwarm.

---

## Repair Interaction

An agent may interact with a damaged region when its simulated position satisfies the environment's repair condition.

A successful interaction can trigger a repair event in the environment.

The agent itself should not directly modify global tissue state unless the environment interface explicitly permits the operation.

This separation keeps agent decision-making distinct from environment state management.

---

## Health and Failure

Agents may maintain an operational health state.

A degraded or failed agent can be excluded from normal decision-making according to the experiment configuration.

This enables experiments investigating swarm robustness and the effect of agent failures on reconstruction performance.

---

## Design Principle

The agent model follows three principles:

### Decentralization

Agents make decisions independently using available local information.

### Hybrid Intelligence

Learned policies can be combined with interpretable heuristics and swarm signals.

### Environmental Coordination

Agents can coordinate indirectly through changes in the shared simulation environment.

---

## Research Role

The agent is the fundamental autonomous unit of the NanoSwarm architecture.

Its behavior provides the connection between:

* the tissue environment
* reinforcement learning
* swarm communication
* navigation
* repair
* system-level performance

Consequently, changes to the agent decision policy can be evaluated through the experiment framework and measured using the project's quantitative metrics.

---

## Modeling Boundary

The term "nanobot" refers to a **simulated computational agent**.

The model does not represent a physically validated nanoscale robot and does not establish that such an agent could operate inside biological tissue.

Agent movement, sensing, communication, health, and repair interactions are abstractions defined for computational experimentation.
